version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    ignore:
      - dependency-name: standard
      - dependency-name: hallmark
      - dependency-name: tempy
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
